### ISSUE TITLE
Define context

### ISSUE THREAD

**Issue by dkruckemyer-ventana** [riscv/riscv-plic-spec#10]
The PLIC spec refers to "contexts" in many places but the term is not clearly defined.

Are these truly software contexts, i.e. software threads? Or does context refer to harts?

If the former, how does one direct different contexts onto a single hart? If the latter, why not refer to them as harts in the document?

Also, how does one map a context to different modes, e.g. S-mode or M-mode?

**Comment by dkruckemyer-ventana** [comment]
Actually, it seems the definition is located in the "Interrupt Enables" section (apologies for sloppy searching), though does leaving the context to {hart, priv mode} mapping as imp-def cause any discovery or handling challenges? Would the OS benefit from any standardization here?

**Comment by aswaterman** [comment]
In practice, PLIC contexts are 1:1 with harts' interruptible privilege modes.  (e.g. if you have 3 harts, each of which supports taking interrupts into M-mode and S-mode, you have 6 contexts.)

I haven't looked at the spec lately, but agree the spec is deficient if that isn't clear from reading it.

**Comment by dkruckemyer-ventana** [comment]
This is the quote in the current text of the "Interrupt Enables" section:

"The context is referred to the specific privilege mode in the specific Hart of specific RISC-V processor instance."

It might make sense to define that up front since it's a key concept.

The other nit I have is the following (which is the sentence following the above):

"How PLIC organizes interrupts for the contexts (Hart and privilege mode) is out of RISC-V PLIC specification scope, however it must be spec-out in vendor’s PLIC specification."

I understand the reasons for this flexibility, but I don't know enough about the device tree entries/discovery software and the ISR/handler code to know whether this flexibility is too difficult to manage.

For PLICv1, maybe this ship has sailed, but for PLICv2, does it make sense to define some structure so that the assignment isn't completely arbitrary?

**Comment by changab** [comment]
> "The context is referred to the specific privilege mode in the specific Hart of specific RISC-V processor instance."
> 
> It might make sense to define that up front since it's a key concept.

Agree. I will move this to upfront at the beginning of this spec.

**Comment by changab** [comment]
> "How PLIC organizes interrupts for the contexts (Hart and privilege mode) is out of RISC-V PLIC specification scope, however it must be spec-out in vendor’s PLIC specification."
I understand the reasons for this flexibility, but I don't know enough about the device tree entries/discovery software and the ISR/handler code to know whether this flexibility is too difficult to manage.

Having a standard way to describe the organization of context helps system firmware to build up DT without platform-specific drivers. S-mode program can afterward refer to DT and understand how interrupts are connected to harts/privilege modes if SMode program rather uses DT than accesses to PLIC register blocks.
PLICv2 has been talked since this PLIC-spec was written. Do we have PLICv2 spec yet? or the draft?

**Comment by changab** [comment]
> Sure, I was just wondering if we can place constraints on the ordering/organization of the PLIC contexts that would simplify the SW task, both in terms of specification (filling out the DT) as well as discovery (parsing the DT). If folks feel that this is pretty simple to manage and is relatively bug free as is, then there's no issue here.

Standardization is always better than defined in the platform spec. We should consider to standardized the organization of context/hart #/privilege mode in PLICv2 spec.

**Comment by changab** [comment]
Fix at https://github.com/riscv/riscv-plic-spec/commit/7cabd4b0585340bae4381439a39ab47899a2688e
