### ISSUE TITLE
Memory map

### ISSUE THREAD

**Issue by dkruckemyer-ventana** [riscv/riscv-plic-spec#11]
The PLIC memory map requires 64MB of memory mapped system address space (26b), largely because the threshold and claim/complete registers are sparsely populated (one 4KB region per context).

Why are these registers spread apart in the address map when the other per-context control registers are not also spread apart? For example, the per-context interrupt enable bits are packed together in the address space.

Also the threshold and claim/complete registers for context 15871 should be at the base address of 0x5DFF000 (if my math is correct), which implies an even larger address space requirement.

**Comment by aswaterman** [comment]
The rationale for the original design is that claim/complete would be on separate pages so that a hypervisor could use paging to grant access to those registers to a guest.

Without a redesign, it's not safe to grant a less-privileged mode access to the enables, so there was no motivation to space them out.

**Comment by aswaterman** [comment]
BTW, if you are willing to limit the number of contexts to 500 or so, you can truncate the memory map to 4 MiB.

**Comment by dkruckemyer-ventana** [comment]
> 
> 
> The rationale for the original design is that claim/complete would be on separate pages so that a hypervisor could use paging to grant access to those registers to a guest.

That's what I figured...

> 
> Without a redesign, it's not safe to grant a less-privileged mode access to the enables, so there was no motivation to space them out.

... but aren't the enables organized per context? Or is this the "protection/permission" mechanism that allows more privileged software to assign interrupt sources to contexts?

For PLICv2, would it be useful to define a mechanism for a given context to manage it's own enables (and priorities)? Is this creeping dangerously close to virtualization....?

**Comment by dkruckemyer-ventana** [comment]
> 
> 
> BTW, if you are willing to limit the number of contexts to 500 or so, you can truncate the memory map to 4 MiB.

Is limiting the number of contexts explicitly allowed by the specification? The memory map perhaps implies otherwise, i.e. there are 15000+ contexts defined, but nowhere does the spec describe what's allowed if fewer are implemented (so I'm left to believe the unimplemented ones are "reserved").

**Comment by changab** [comment]
> Is limiting the number of contexts explicitly allowed by the specification? The memory map perhaps implies otherwise, i.e. there are 15000+ contexts defined, but nowhere does the spec describe what's allowed if fewer are implemented (so I'm left to believe the unimplemented ones are "reserved").

You can have a smaller memory block for the operation register block, but the base address of each operation register block is fixed and defined in this PLICv1 spec already. Apparently you will have a big space between operation register blocks with fewer interrupt sources.

**Comment by changab** [comment]
> Regarding the offset for context 15871, my math was incorrect (I added an extra zero for the start of the per-context threshold/claim/complete region), but there's still a typo:
> 
> * The offset for context pages is 0x200000
> * The additional offset for context 15871 is 15871*0x1000 = 0x3DFF000
> * So the actual offset for context 15871 is 0x3FFF000
> 
> The spec states 0x3FFE000.

Ah, yes you are right. It should be 0x3FFF000 for the last context 15871.
