### ISSUE TITLE
Questions regarding gateways

### ISSUE THREAD

**Issue by dkruckemyer-ventana** [riscv/riscv-plic-spec#12]
Figure 2 draws a distinction between the PLIC core and PLIC gateways. Are the latter intended to be defined in the PLIC spec? If so, what is the intended functionality of the gateway and does software have an interface to those gateways?

Note that the claim register implies that the gateway masks the "Interrupt N Signals" and thus deasserts the "Interrupt Request" signal and clears the "Source's IP" signal (assuming IP = interrupt pending). Does a corresponding access to the complete register reverse this process, i.e. unmask the "Interrupt N Signals," which possibly asserts the "Interrupt Request" and "Source's IP" signal, if the "Interrupt N Signals" are still asserted?

Finally, what are the signalling requirements for "Interrupt N Signals" to the gateways? Is the assignment of polarity and level vs. edge to each input signal external to the PLIC spec?

**Comment by changab** [comment]
> Figure 2 draws a distinction between the PLIC core and PLIC gateways. Are the latter intended to be defined in the PLIC spec? If so, what is the intended functionality of the gateway and does software have an interface to those gateways?

As my understanding, the gateway is very platform implementation-specific, even the level/or edge trigger of interrupt sources is based on the platform design, software can't access gateway and configure the interrupt trigger mode in PLIC v1 spec. We will have to address this in PLICv2 to support different trigger mode of devices. Gateway is mentioned in RISC-V privilege spec v1.9 and  I believe that is sort of guidance of PLIC implementation (also SiFive's PLIC implementation).

**Comment by changab** [comment]
>Finally, what are the signalling requirements for "Interrupt N Signals" to the gateways? Is the assignment of polarity and level vs. edge to each input signal external to the PLIC spec?

There is no requirements for this if my understanding is correct, that is platform implementation.

**Comment by changab** [comment]
> Note that the claim register implies that the gateway masks the "Interrupt N Signals" and thus deasserts the "Interrupt Request" signal and clears the "Source's IP" signal (assuming IP = interrupt pending). Does a corresponding access to the complete register reverse this process, i.e. unmask the "Interrupt N Signals," which possibly asserts the "Interrupt Request" and "Source's IP" signal, if the "Interrupt N Signals" are still asserted?

The corresponding behavior was ever described in RISC-V privilege v1.9 released in 2016. You may refer to chapter 7 PLIC and 7.4  Interrupt Gateways for the details.

**Comment by changab** [comment]
> Finally, if there's some implied specification that this specification is based on, please refer to that source specification and (ideally) provide a link to the spec.

That spec was gone from RISC-V privilege. I am considering to pull in that spec (with further modifications) into this one on Github. How do you think?

**Comment by dkruckemyer-ventana** [comment]
> That spec was gone from RISC-V privilege. I am considering to pull in that spec (with further modifications) into this one on Github. How do you think?

If there's useful background or additional functional information that is no longer accessible in the original spec, I would say it should be moved to this specification. Tough to say without seeing the old spec though....

**Comment by changab** [comment]
ok. I will pull that information in this spec. thanks

**Comment by axel-h** [comment]
@changab: Have you pulled it over? I have created the PR https://github.com/riscv/riscv-isa-manual/pull/693 now to push for a clean cut here as I found it very confusing that it slightly unclear where detailed background information about the PLIC concepts can be found and where further clarification should happen.

**Comment by changab** [comment]
Oops..I missed many PRs and issues on this repo. 

I just sent PR for this issue. Please review it. Thanks
https://github.com/riscv/riscv-plic-spec/pull/25

**Comment by changab** [comment]
https://github.com/riscv/riscv-plic-spec/pull/25 is merged. The original PLIC spec was pulled over.
