### ISSUE TITLE
Number of priorities

### ISSUE THREAD

**Issue by dkruckemyer-ventana** [riscv/riscv-plic-spec#13]
What is the range of priority levels supported by the PLIC? Is there a max number?

**Comment by changab** [comment]
The maximum level of priority depends on the PLIC implementation.

**Comment by changab** [comment]
Same thought here with the above suggestions. Actually what you mentioned had ever mentioned in the PLIC DT spec here (already removed) and the draft PLIC MADT spec in ACPI as well (see https://github.com/riscv/riscv-plic-spec/blob/master/riscv-plic-acpi.adoc). But those are not defined in the operational register blocks though.

**Comment by dkruckemyer-ventana** [comment]
Thanks for pointing me to that structure. I believe that captures most of the information. A reference in the PLIC spec would be helpful for hardware designers to understand what parameters there are.

One question though... It seems that the HCID entries should be one per context (i.e. one per {hart, priv} tuple) rather than one per hart (n), since each hart could have multiple interrupt contexts (e.g. supervisor and machine). Unless the HCID structure accommodates multiple privilege levels in a way I'm not seeing?

**Comment by changab** [comment]
yes. HCID is context-based, you can have multiple  HCIDs for the same hart but different privilege modes.
This ACPI PLIC spec is originally created to support PLIC flexibly, e.g. the base address to the operation region blocks is not fixed. However, this may be too much for PLIC v1 but could be the benefit to small system.

**Comment by dkruckemyer-ventana** [comment]
Note, however, that the Length field equals 28 + n + (n*x), where n equals the number of harts (as defined by the PLIC Target Hart ID field) and x equals the size of the HCID table. But since each hart can have multiple contexts, there really should be a different number, say m, where m >= n, that is the total number of contexts. I believe the number m is specified by the "Number of Hart Context Interrupt Description Structures" field, and so the size of the HCID structures would be (m*x).

Adding it all up then, the Length field seems to equal 33 + n + (m*x), where x appears to equal 16. The fixed value of 28 seems to be incorrect.

Also, I believe there are a couple of byte offset errors in the table. In particular, "Maximum Interrupt Priority Levels" should be at 17+n, and "Hart Context Interrupt Description (HCID) Structures" should be at 33+n.

**Comment by dkruckemyer-ventana** [comment]
> 

> This ACPI PLIC spec is originally created to support PLIC flexibly, e.g. the base address to the operation region blocks is not fixed. However, this may be too much for PLIC v1 but could be the benefit to small system.

Yeah, I see that now, and I understand how Andrew can get his 4MB PLIC region in https://github.com/riscv/riscv-plic-spec/issues/11

**Comment by changab** [comment]
> Note, however, that the Length field equals 28 + n + (n * x), where n equals the number of harts (as defined by the PLIC Target Hart ID field) and x equals the size of the HCID table. But since each hart can have multiple contexts, there really should be a different number, say m, where m >= n, that is the total number of contexts. I believe the number m is specified by the "Number of Hart Context Interrupt Description Structures" field, and so the size of the HCID structures would be (m * x).
> 
> Adding it all up then, the Length field seems to equal 33 + n + (m*x), where x appears to equal 16. The fixed value of 28 seems to be incorrect.
> 
> Also, I believe there are a couple of byte offset errors in the table. In particular, "Maximum Interrupt Priority Levels" should be at 17+n, and "Hart Context Interrupt Description (HCID) Structures" should be at 33+n.

Thanks for catching these. I will review this again once we we have a firmed PLIC v1 spec.
