### ISSUE TITLE
PDF/HTML of PLIC specification?

### ISSUE THREAD

**Issue by jstraus59** [riscv/riscv-plic-spec#14]
Would it be possible to make a PDF and/or HTML version of the PLIC document available in a Github release, as is done for other riscv specs (e.g. [riscv-v-spec](https://github.com/riscv/riscv-v-spec/releases/tag/0.9) and [riscv-isa-manual](https://github.com/riscv/riscv-isa-manual/releases/tag/Ratified-IMAFDQC))

**Comment by changab** [comment]
Done
