### ISSUE TITLE
Wrong offset in memory map

### ISSUE THREAD

**Issue by ppeetteerrs** [riscv/riscv-plic-spec#16]
**Original:**
base + 0x3FFE000: Priority threshold for context 15871
base + 0x3FFE004: Claim/complete for context 15871
base + 0x3FFE008: Reserved

**It should be:**
base + 0x3FFF000: Priority threshold for context 15871
base + 0x3FFF004: Claim/complete for context 15871
base + 0x3FFF008: Reserved

**Comment by changab** [comment]
The fix is merged.
