### ISSUE TITLE
Unclear language in interrupt completion section

### ISSUE THREAD

**Issue by darius-bluespec** [riscv/riscv-plic-spec#30]
The interrupt completion section may be unclear and appears to include implementation details of the SiFive PLIC as opposed to a specification.  The wording in question is:

> The PLIC does not check whether the completion ID is the same as the last claim ID for that target. If the completion ID does not match an interrupt source that is currently enabled for the target, the completion is silently ignored.

See https://lists.infradead.org/pipermail/linux-riscv/2021-October/009222.html for some background

**Comment by aswaterman** [comment]
Not sure why you’d call this an implementation detail: it’s ISA-visible hence needs to be part of the spec.
