### ISSUE TITLE
Error in Section 6 "Interrupt Enables"

### ISSUE THREAD

**Issue by michaelengel** [riscv/riscv-plic-spec#36]
Section 6 lists the PLIC addresses for the IE bits as follows:

```
0x002000: Interrupt Source #0 to #31 Enable Bits on context 0
...
0x00207F: Interrupt Source #992 to #1023 Enable Bits 
```
(and so on).

Since each interrupt enable register is four byte wide (as it holds 32 bits of enables), the base address for the Interrupt Source #992 to #1023 Enable Bits should be 0x00207C, not 0x00207F (the same change is required for the other contexts shown).

**Comment by changab** [comment]
Fix @d14e8a91c7f6b8718fa662ae837eb3fccb7a5911
