### ISSUE TITLE
Ambiguity in handling deferred IRQs

### ISSUE THREAD

**Issue by zetalog** [riscv/riscv-plic-spec#9]
My confusion is related to this statement:
```
If the completion ID does not match an interrupt source that is currently enabled for the target, the completion is silently ignored.
```

For realtime reason, an level triggered IRQ (ASAIK, all PLIC IRQs are level triggered) handler may not be able to complete an IRQ in time in the IRQ context. The hardware driver may choose to defer handling this IRQ in the task context. And the driver code may look like:
```
irq_irq_handler()
{
  mask irq
  schedule task_irq_handler
}

task_irq_handler()
{
  handle irq
  ack irq (clear irq)
  unmask irq
}
```

An IRQ controller that is ARM GIC like has claim/completion process.

As far as I know, there are GIC vendor variations implementing GICv2 in the way that if an IRQ is not completed and the IRQ handler returns, other IRQs that have same priority cannot arrive to the same CPU unless the previous claimed IRQ is completed. In order not to block other IRQs when an IRQ is handling in the deferred way, OSen will implement GIC like driver in this way:
```
gic_handle_irq()
{
  claim irq
  call irq_irq_hanlder
  complete irq
}
```

Then we clearly can see a sequence (sequence A) that:
```
claim irq
mask irq
complete irq
handle irq
ack irq (clear irq)
unmask irq
```

However if GIC allows other IRQs in the same priority arrive when one of them is not completed but claimed, the sequence (sequence B) can be:
```
claim irq
mask irq
handle irq
ack irq (clear irq)
unmask irq
eoi irq (complete irq)
```
This makes senses, but the SPEC also has no statement about this sequence. And hardware vendor may provide GIC like implementation.

|Completion style|Concerns|
|--- |--- |
|B|There is no clear statement in the PLIC spec enforcing this. This brings ambiguity and implementation variation problems to the vendors.|
|A|Unfortunately PLIC only has IRQ enabling/disabling register, and doesn't have masking/unmasking register. And we may use PRIORITYR to achieve masking/masking for PLIC. Let's discussed the 2 masking approaches in the next table.|

|Style A masking solution|Concerns|
|--- |--- |
|ENABLER|For such kind of IRQ controller, OSen will use disabling/enabling count to implement both IRQ masking/unmasking and disabling/enabling. When disabling count>0, IRQ is masked, when disabling count=0, IRQ is unmasked; when enabling count>0, IRQ is enabled, when enabling count=0, IRQ is disabled; masking should be done for a enabled IRQ. It surely cannot avoid complete when IRQ is disabled.|
|PRIORITYR|It shall require IRQ controller driver to save previous configured IRQ priority (IRQ controller driver doesn't have knowledge about it, it's up to the hardware drivers' usage model) when an IRQ is masked. This seems to be wired as it costs additional memory consumption in IRQ controller driver.|

So my questions are:
1. Which style is PLIC completion preferred? And if the sequence B is preferred, should it be stated in the SPEC?
2. If sequence A is preferred, can the statement in question be detailed for the deferred handling cases? How such case is meant to be handled in the PLIC environment.

**Comment by changab** [comment]
Hi @zetalog,
Could https://github.com/riscv/riscv-plic-spec/blob/master/riscv-plic.adoc#interrupt-flow fix your concern?
